apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hv3vdmhrw-nodejs
  janus-idp.io/tekton: hv3vdmhrw-nodejs
  backstage.io/kubernetes-id: hv3vdmhrw-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hv3vdmhrw-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
