apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hv3vdmhrw-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hv3vdmhrw-nodejs 
  name: hv3vdmhrw-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: hv3vdmhrw-nodejs 
